### PR TITLE
Update to latest gradle and android library versions.

### PR DESCRIPTION
**Pull request by IgorGanapolsky**

### CODE REVIEW

**Comment by jbj88817** [comment]
Hi Igor, Thanks for updating. I am really appreciated.

**Comment by IgorGanapolsky** [comment]
Sure.  However, your map still doesn't load in the third tab.  Do you know
why I'm getting a blank map?  I put the correct api key in AndroidManifest,
and added SHA key in Google Dev console...

Thanks,
Igor

**Comment by jbj88817** [comment]
Hi Igor,

I tried again, and I could load map on my side. The API KEY which provide in this is server key which can take any request from anywhere.

Regards,
Bojie

**Comment by IgorGanapolsky** [comment]
Server key?  What do you mean, o thought it is am Android key.

**Pull request merged**
